// THIS SCRIPT WILL BE USED TO HANDLE THE LOGIC FOR CHECKING ANSWERS ON EACH RIDDLE PAGE.

LET CORRECTANSWER = ""; // TO STORE THE CORRECT ANSWER FOR EACH RIDDLE

// THIS FUNCTION SETS THE CORRECT ANSWER FOR THE CURRENT RIDDLE
FUNCTION SETCORRECTANSWER(ANSWER) {
  CORRECTANSWER = ANSWER;
}

// THIS FUNCTION CHECKS THE USER'S ANSWER
FUNCTION CHECKANSWER() {
  CONST USERANSWER = DOCUMENT.GETELEMENTBYID("ANSWER-INPUT").VALUE.TOLOWERCASE().TRIM();
  CONST FEEDBACK = DOCUMENT.GETELEMENTBYID('FEEDBACK');
  CONST EMOJI = DOCUMENT.GETELEMENTBYID('EMOJI');

  IF (USERANSWER === CORRECTANSWER) {
    FEEDBACK.TEXTCONTENT = "CORRECT! WELL DONE!";
    EMOJI.TEXTCONTENT = "😊"; // SMILEY FACE FOR CORRECT ANSWER
    FEEDBACK.CLASSLIST.REMOVE("INCORRECT");
    FEEDBACK.CLASSLIST.ADD("CORRECT");

    // DISPLAY THE NEXT BUTTON OR FINISH BUTTON, DEPENDING ON THE RIDDLE
    CONST NEXTBUTTON = DOCUMENT.GETELEMENTBYID("NEXT-RIDDLE");
    CONST FINISHBUTTON = DOCUMENT.GETELEMENTBYID("FINISH-GAME");

    IF (NEXTBUTTON) {
      NEXTBUTTON.STYLE.DISPLAY = "INLINE-BLOCK"; // SHOW NEXT BUTTON FOR RIDDLE 1 AND 2
    }
    IF (FINISHBUTTON) {
      FINISHBUTTON.STYLE.DISPLAY = "INLINE-BLOCK"; // SHOW FINISH BUTTON FOR THE LAST RIDDLE
    }

    // DISABLE THE INPUT AND SUBMIT BUTTON AFTER ANSWERING
    DOCUMENT.GETELEMENTBYID("ANSWER-INPUT").DISABLED = TRUE;
    DOCUMENT.QUERYSELECTOR("BUTTON").DISABLED = TRUE;
  } ELSE {
    FEEDBACK.TEXTCONTENT = "OOPS, TRY AGAIN!";
    EMOJI.TEXTCONTENT = "😞"; // SAD FACE FOR INCORRECT ANSWER
    FEEDBACK.CLASSLIST.REMOVE("CORRECT");
    FEEDBACK.CLASSLIST.ADD("INCORRECT");
  }
}

// THIS FUNCTION MOVES THE USER TO THE NEXT RIDDLE PAGE
FUNCTION NEXTRIDDLE() {
  IF (WINDOW.LOCATION.PATHNAME.INCLUDES("RIDDLE1.HTML")) {
    WINDOW.LOCATION.HREF = 'RIDDLE2.HTML'; // GO TO RIDDLE 2
  } ELSE IF (WINDOW.LOCATION.PATHNAME.INCLUDES("RIDDLE2.HTML")) {
    WINDOW.LOCATION.HREF = 'RIDDLE3.HTML'; // GO TO RIDDLE 3
  }
}

// THIS FUNCTION FINISHES THE GAME AND REDIRECTS TO THE THANK YOU PAGE
FUNCTION FINISHGAME() {
  WINDOW.LOCATION.HREF = 'THANKYOU.HTML'; // GO TO THE THANK YOU PAGE
}

// THIS FUNCTION WILL BE CALLED WHEN THE PAGE LOADS TO SET THE CORRECT ANSWER BASED ON THE RIDDLE PAGE
WINDOW.ONLOAD = FUNCTION () {
  IF (WINDOW.LOCATION.PATHNAME.INCLUDES("RIDDLE1.HTML")) {
    SETCORRECTANSWER("PIANO"); // SET THE ANSWER FOR RIDDLE 1
  } ELSE IF (WINDOW.LOCATION.PATHNAME.INCLUDES("RIDDLE2.HTML")) {
    SETCORRECTANSWER("ECHO"); // SET THE ANSWER FOR RIDDLE 2
  } ELSE IF (WINDOW.LOCATION.PATHNAME.INCLUDES("RIDDLE3.HTML")) {
    SETCORRECTANSWER("DARKNESS"); // SET THE ANSWER FOR RIDDLE 3
  }
};
